# Generated by Django 4.2 on 2026-02-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeplin_project_id', models.CharField(max_length=255)),
                ('zeplin_screen_id', models.CharField(max_length=255)),
                ('live_url', models.URLField(max_length=2000)),
                ('pixel_mismatch_count', models.IntegerField(blank=True, null=True)),
                ('css_mismatch_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design_image', models.ImageField(blank=True, null=True, upload_to='design/')),
                ('live_image', models.ImageField(blank=True, null=True, upload_to='live/')),
                ('diff_image', models.ImageField(blank=True, null=True, upload_to='diff/')),
                ('raw_json_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
