# Generated by Django 4.2 on 2026-02-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationreport',
            name='dom_node_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationreport',
            name='js_error_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationreport',
            name='zeplin_layer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
