# Generated by Django 4.2 on 2026-02-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_validationreport_dom_node_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationreport',
            name='mismatch_regions',
            field=models.JSONField(blank=True, help_text='Stored geometric location data (x, y, w, h)', null=True),
        ),
    ]
